# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestUntitled():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_untitled(self):
    # Test name: Untitled
    # Step # | name | target | value
    # 1 | open | / | 
    self.driver.get("https://www.mercadolibre.com.mx/")
    # 2 | setWindowSize | 1936x1048 | 
    self.driver.set_window_size(1936, 1048)
    # 3 | click | id=cb1-edit | 
    self.driver.find_element(By.ID, "cb1-edit").click()
    # 4 | type | id=cb1-edit | carro rojo
    self.driver.find_element(By.XPATH, "//input[@id='cb1-edit']").send_keys("carro rojo")
    # 5 | click | css=.nav-icon-search | 
    self.driver.find_element(By.CSS_SELECTOR, ".nav-icon-search").click()
    # 6 | click | linkText=Ferrari F1-75 2022 Charles Leclerc #16 Ed. Esp. Burago 1/18 Color Rojo | 
    self.driver.find_element(By.LINK_TEXT, "Ferrari F1-75 2022 Charles Leclerc #16 Ed. Esp. Burago 1/18 Color Rojo").click()
    # 7 | mouseOver | css=#quantity-selector > .andes-button__content | 
    element = self.driver.find_element(By.CSS_SELECTOR, "#quantity-selector > .andes-button__content")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    # 8 | click | css=#\3AR2cqakck4um\3A > .andes-button__content | 
    self.driver.find_element(By.CSS_SELECTOR, "#\\3AR2cqakck4um\\3A > .andes-button__content").click()
    # 9 | mouseOver | css=#\3AR2cqakck4um\3A > .andes-button__content | 
    element = self.driver.find_element(By.CSS_SELECTOR, "#\\3AR2cqakck4um\\3A > .andes-button__content")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    # 10 | mouseOut | css=#\3AR2cqakck4um\3A > .andes-button__content | 
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    # 11 | close |  | 
    self.driver.close()
  
